project_name: zswchain-aliyun-kms-go
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/zhongshuwen/zswchain-aliyun-kms-go:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/zhongshuwen/zswchain-aliyun-kms-go
  - --label=org.opencontainers.image.source=https://github.com/goreleaser/zswchain-aliyun-kms-go
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2022-02-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: 中数文 <it@zhongshuwen.com>
  description: 中数文联盟链go sdk demo
  homepage: https://zhongshuwen.com
  license: MIT
  formats:
  - deb
  - rpm
  - apk
